--- #YAML:1.0
name:               Compress-Snappy
version:            0.01
abstract:           Perl interface to Google's Snappy (de)compressor
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    parent:  0
resources:
    repository:  http://github.com/gray/compress-snappy
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
