---
abstract: "Perl interface to Google's Snappy (de)compressor"
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: 0.82
configure_requires:
  Devel::CheckLib: 0
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compress-Snappy
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.57
  XSLoader: 0
resources:
  repository: http://github.com/gray/compress-snappy
version: 0.23
